### ISSUE TITLE
Option Fsresidual not working with methods other than OP or LP

### ISSUE THREAD

**Issue by skbormann** [GabrieleRovigatti/prodest#7]
Hi,
The option _fsresidual(newname)_ does not work with methods than OP or LP in the Stata code.

This problem could be reproduced so far with two different datasets including the example dataset provided with the package.
The problem occurs somewhere between the lines 546 - 551 where the temp file gets created and saved and lines 650 - 652 where the temp file should get merged with original dataset.
The attached log file [prodest_error.log](https://github.com/GabrieleRovigatti/prodest/files/2190527/prodest_error.log) shows an example session. The example dataset gets loaded and described. The version number of the package is reported and the result of **creturn list** is shown. Afterwards the prodest command is called for the OP and LP method without problems, while using the WRDG and ROB method results in an **invalid file specification** error.
If needed, I could provide an output from a command run with **set trace on**.

Best regards
Sven-Kristjan

**Comment by GabrieleRovigatti** [comment]
Hi,

you were right, thanks for pointing that out. 

Correctly, the _fsresidual(newname)_  option works with OP and LP only (plus their ACF correction versions), since these are two-steps models. In the new version of the command I added the error 

> fsresiduals is available with OP and LP methods only.

in case the user specifies the option with methods other than OP and LP.

Thanks, 

Gabriele
